name: Git Pull CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: delicatest.com
        username: root
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /var/www/kuanyshkz/
          git pull
